ICONS = {
    "record": "●",
    "play": "▶",
    "stop": "■",
    "capture": "📸",
    "image": "🖼",
    "region": "▭",
    "save": "💾",
    "load": "📂",
    "folder": "🗂",
    "insert": "↳",
    "clear": "✖",
    "step": "⏭",
    "continue": "⏩",
}
